telefonrehber/Models/kisi.cs
namespace telefonrehber.Models
{
    public class kisi
    {
        public int id { get; set; }
        public string ad { get; set; }
        public string telefon { get; set; }
<<<<<<< HEAD

=======
      
>>>>>>> 961afc2caab843f24c758815fd033a436f69f418
    }
}

telefonrehber/Controllers/kisisController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using telefonrehber.Data;
using telefonrehber.Models;
using Microsoft.AspNetCore.Http;
using Newtonsoft.Json;

namespace telefonrehber.Controllers
{
   

    public static class SessionExtensions
    {
        public static void SetObject(this ISession session, string key, object value)
        {
            session.SetString(key, JsonConvert.SerializeObject(value));
        }

        public static T GetObject<T>(this ISession session, string key)
        {
            var value = session.GetString(key);
            return value == null ? default(T) : JsonConvert.DeserializeObject<T>(value);
        }
    }

    public class kisisController : Controller
    {

        private readonly AppDbContext _context;
         private readonly IHttpContextAccessor _httpContextAccessor;

        {
            _context = context;
            _httpContextAccessor = httpContextAccessor;

        }

        // GET: kisis
        public async Task<IActionResult> Index()
        {
            return View(await _context.kisiler.ToListAsync());
        }

        // GET: kisis/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kisi = await _context.kisiler
                .FirstOrDefaultAsync(m => m.id == id);
            if (kisi == null)
            {
                return NotFound();
            }

            return View(kisi);
        }

        // GET: kisis/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: kisis/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("id,ad,telefon")] kisi kisi)
        {
            if (ModelState.IsValid)
            {
                _context.Add(kisi);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(kisi);
        }

        // GET: kisis/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kisi = await _context.kisiler.FindAsync(id);
            if (kisi == null)
            {
                return NotFound();
            }
            return View(kisi);
        }

        // POST: kisis/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("id,ad,telefon")] kisi kisi)
        {
            if (id != kisi.id)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(kisi);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!kisiExists(kisi.id))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(kisi);
        }

        // GET: kisis/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var kisi = await _context.kisiler
                .FirstOrDefaultAsync(m => m.id == id);
            if (kisi == null)
            {
                return NotFound();
            }

            return View(kisi);
        }

        // POST: kisis/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var kisi = await _context.kisiler.FindAsync(id);
            if (kisi != null)
            {
                _context.kisiler.Remove(kisi);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool kisiExists(int id)
        {
            return _context.kisiler.Any(e => e.id == id);
        }
        public IActionResult Search(string searchTerm)
        {
            var kisis = _context.kisiler.Where(k => k.ad.Contains(searchTerm) || k.telefon.Contains(searchTerm));
            return Json(kisis.Select(k => new { ad = k.ad, telefon = k.telefon }));
        }
       
      

    
    }
}

telefonrehber/Views/kisis/Create.cshtml
@model telefonrehber.Models.kisi

@{
    ViewData["Title"] = "Create";
}

@* <h1>Create</h1>

<h4>kisi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="ad" class="control-label"></label>
                <input asp-for="ad" class="form-control" />
                <span asp-validation-for="ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefon" class="control-label"></label>
                <input asp-for="telefon" class="form-control" />
                <span asp-validation-for="telefon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div> *@
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <script src="code.js"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body class="bg-dark">
    <div class="container mt-5 pt-5">

        <div class="row mt-5 pt-5">

            <div class="col-md-6 offset-md-3 justify-content-center mt-5 pt-5">

                <h2>Kişi Kaayıt</h2>

                <form asp-action="Create">

                    <div class="form-group">

                        <label for="name" asp-for="ad" class="text-white">isim:</label>
                        <input type="text" asp-for="ad" class="form-control" id="name" required>
                        <span asp-validation-for="ad" class="text-danger"></span>

                    </div>

                    <div class="form-group">

                        <label for="phone" asp-for="telefon" class="text-white">Telefon numarası:</label>

                        <input type="tel" asp-for="telefon" class="form-control" id="phone" maxlength="10" required>
                        <span asp-validation-for="telefon" class="text-danger"></span>

                    </div>
                    <input type="submit" value="Kaydet" class="btn btn-success m-2" />
                    @* <button type="submit" class="btn btn-success m-2" onclick="registerUser()">Kaydet</button> *@

					<button type="button" class="btn btn-outline-primary">  <a asp-action="Index">Back to List</a></button>
                </form>

            </div>

        </div>

    </div>
</body>
</html>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

telefonrehber/Views/kisis/Delete.cshtml
@model telefonrehber.Models.kisi
<<<<<<< HEAD
@{
    ViewData["Title"] = "Delete";
}
<body class="bg-dark text-light">
=======

@{
    ViewData["Title"] = "Delete";
}

>>>>>>> 961afc2caab843f24c758815fd033a436f69f418
<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>kisi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefon)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="id" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
<<<<<<< HEAD
        <button asp-action="Index" class="btn btn-primary">Back to List</button>
        @* <a asp-action="Index">Back to List</a> *@
    </form>
</div>
</body>
=======
        <a asp-action="Index">Back to List</a>
    </form>
</div>
>>>>>>> 961afc2caab843f24c758815fd033a436f69f418

telefonrehber/Views/kisis/Details.cshtml
@model telefonrehber.Models.kisi

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>kisi</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.ad)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.ad)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.telefon)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.telefon)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model?.id">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

telefonrehber/Views/kisis/Edit.cshtml
@model telefonrehber.Models.kisi

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>kisi</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="id" />
            <div class="form-group">
                <label asp-for="ad" class="control-label"></label>
                <input asp-for="ad" class="form-control" />
                <span asp-validation-for="ad" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="telefon" class="control-label"></label>
                <input asp-for="telefon" class="form-control" />
                <span asp-validation-for="telefon" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

telefonrehber/Views/kisis/Index.cshtml
@model IEnumerable<telefonrehber.Models.kisi>

@{
    ViewData["Title"] = "Index";
<<<<<<< HEAD
    List<kisi> listecik = new List<kisi>();
}


<script src="~/js/site.js"></script>
<body class="bg-dark">
    <div class="container-fluid d-flex align-items-center justify-content-center" style="height: 100vh; flex-direction: column;">
        <div class="mx-auto offset-md-3 col-md-6 d-flex justify-content-center">
            <div class="d-flex justify-content-between d-flex align-items-center">
                <form class="d-flex align-items-center" style="width: 400px;">
                    <input class="form-control mr-sm-2" id="search-input" type="search" placeholder="Search" aria-label="Search">
                    <button class="btn btn-outline-success my-2 my-sm-0 mx-2" id="search-button" type="button">Search</button>
                </form>
            </div>
        </div>

        <div class="mx-auto offset-md-3 col-md-5 justify-content-center d-flex pt-5">
            <div class="d-flex align-items-md-center">
                <div class="d-flex">
                    <div>
                        <h3 class="text-white">Ad Soyad</h3>
                        <div class="col-lg mx-2">
                            <ul class="list-group" id="list-group" style="width: 200px;">
                                @foreach (var item in Model)
                                {
                                    <li class="list-group-item" style="height:55px;">
                                        <span class="name">@Html.DisplayFor(modelItem => item.ad)</span>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                    <div>
                        <h3 class="text-white">TEL NO</h3>
                        <div class="col-lg mx-2">
                            <ul class="list-group" id="phone-list-group" style="width: 200px;">
                                @foreach (var item in Model)
                                {
                                    <li class="list-group-item text-end mx-3" style="width:200px;">
                                        <button asp-controller="kisis" asp-action="Delete" asp-route-id="@item.id" class='btn btn-danger'>
                                            <a asp-controller="kisis" asp-action="Delete" asp-route-id="@item.id">delete</a>
                                        </button>
                                        <span class="phone">@Html.DisplayFor(modelItem => item.telefon)</span>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>
                </div>
            </div>
        </div>

        <div class="pt-5">
            <button type="button" class="btn btn-outline-primary">
                <a asp-area="" asp-controller="SearchHistory" asp-action="Index">Privacy</a>
                </button>
            <button type="button" class="btn btn-outline-success">
                <a asp-action="Create">Create New</a>
            </button>
        </div>
    </div>

    <script>
        function search() {
            var input, filter, nameList, phoneList, nameItems, phoneItems, i, nameValue, phoneValue;
            input = document.getElementById('search-input');
            filter = input.value.toUpperCase();
            nameList = document.getElementById("list-group");
            phoneList = document.getElementById("phone-list-group");
            nameItems = nameList.getElementsByTagName('li');
            phoneItems = phoneList.getElementsByTagName('li');

            for (i = 0; i < nameItems.length; i++) {
                nameValue = nameItems[i].getElementsByClassName("name")[0].innerText.toUpperCase();
                phoneValue = phoneItems[i].getElementsByClassName("phone")[0].innerText.toUpperCase();
                if (nameValue.indexOf(filter) > -1 || phoneValue.indexOf(filter) > -1) {
                    nameItems[i].style.display = "";
                    phoneItems[i].style.display = "";
                } else {
                    nameItems[i].style.display = "none";
                    phoneItems[i].style.display = "none";
                }
            }

            let data = {
                keyword: input.value
            };
            fetch("https://localhost:7012/SearchHistory/Add", {
                method: "POST",
                headers: {
                    "Content-Type": "application/json"
                },
                body: JSON.stringify(data)
            });
        }

        document.getElementById('search-button').addEventListener('click', search);
    </script>
    <script>
      
                $("#searchInput").autocomplete({
                source: function (request, response) {
                $.ajax({
                });
                url: @Url.Action("GetSearchValue", "Home")', dataType: "json",
                data: search: $("#searchInput").val() }, success: function (data) {
                },
                response($.map(data, function (item) { return {label:item.Name, value:item.Name}|
                }));
                error: function (xhr, status, error) { alert("Error");
    </script>
</body> 
=======
}

@* <h1>Index</h1>

<p>
    <a asp-action="Create">Create New</a>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.ad)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.telefon)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.ad)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.telefon)
            </td>
            <td>
                <a asp-action="Edit" asp-route-id="@item.id">Edit</a> |
                <a asp-action="Details" asp-route-id="@item.id">Details</a> |
                <a asp-action="Delete" asp-route-id="@item.id">Delete</a>
            </td>
        </tr>
}
    </tbody>
</table> *@
<script src="~/js/site.js"></script>
 <body class="bg-dark" onload="listele()">
        
        <div class="container-fluid d-flex align-items-center justify-content-center " style="height: 100vh; flex-direction: column;">
        <div class=" mx-auto offset-md-3 col-md-6 d-flex justify-content-center">
        <div class="d-flex justify-content-between  d-flex align-items-center" >
            <form class=" d-flex align-items-center" style="width: 400px;">
                <input class="form-control mr-sm-2" id="search-input" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success my-2 my-sm-0 mx-2" id="search-button" onclick="search()" type="button">Search</button>
            </form>
        </div>
        </div>

    <div class="mx-auto offset-md-3 col-md-5 justify-content-center d-flex pt-5 ">
        <div class="d-flex align-items-md-center">
            <div class="d-flex">
                <div>
                    <h3 class="text-white">Ad Soyad</h3>
            <div class="col-lg mx-2 ">
                <ul class="list-group"  style="width: 200px;">
                                @foreach (var item in Model)

                                {

                                    <li class="list-group-item">  @Html.DisplayFor(modelItem => item.ad)</li>

                                }
                </ul>
            </div>
        </div>
            <div>
                <h3 class="text-white">TEL NO</h3>
            <div class="col-lg mx-2">
                <ul class="list-group" style="width: 200px;">
                                @foreach (var item in Model)
                                {
                                    <li class="list-group-item">

                                        @Html.DisplayFor(modelItem => item.telefon)

                                    </li>
                                }
                    
                </ul>
            </div>
    </div>
    </div>

        </div>
    </div>
    <div class="pt-5">
           

                <button type="button" class="btn btn-outline-success"> <a asp-action="Create">Create New</a></button>
                <button type="button" class="btn btn-outline-warning">   <a asp-action="Edit">Edit</a> </button>
                <button type="button" class="btn btn-outline-danger"><a asp-action="Delete" >Delete</a></button>
                <button type="button" class="btn btn-outline-primary"> <a asp-action="Details">Details</a> |</button>
            
    </div>
    
    </div>
    
    </div>
    </div>
   <script>
      
   </script>
    </body>
>>>>>>> 961afc2caab843f24c758815fd033a436f69f418